steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init || exit 1
      
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      terraform plan -var-file=variables.tfvars -out=tf.plan 
      terraform show -json tf.plan >tf.json
      #cat tf.json
# [END tf-plan]

# [START Terraform plan scanning ]
- id: 'Plan Scanning with Checkov'
  name: 'python'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
      checkov -f tf.json -o json >result.json
      echo "**************"
      cat result.json
      echo "**********"
# [END Terraform plan scanning]  

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      #terraform apply -var-file="/workspace/variables.tfvars" -auto-approve || exit 1
# [END tf-apply]      

options:
  logging: CLOUD_LOGGING_ONLY
