steps:
# [START tf-plan]
- id: 'tf init and plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd CloudRun
      pwd
      terraform init
      terraform plan -var-file=variables.tfvars -out=tf.plan 
      terraform show -json tf.plan >tf.json
# [END tf-plan]

# [START Terraform plan scanning ]
- id: 'Plan Scanning with Checkov'
  name: 'python'
  waitFor: 
  - 'tf init and plan'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
      pip install checkov
      #cd CloudStorage
      cd CloudRun
      checkov -f tf.json -o json >result.json --skip-check=CKV_GCP*
      if [ $? == 1 ]; then
        echo "issues in scan, exiting"
        exit 1
      fi
# [END Terraform plan scanning]  

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  waitFor: 
  - 'Plan Scanning with Checkov'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      #cd CloudStorage
      cd CloudRun
      #terraform apply -var-file="variables.tfvars" -auto-approve || exit 1
# [END tf-apply]      

options:
  logging: CLOUD_LOGGING_ONLY
