steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  #waitFor: 'branch name'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init || exit 1
      
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  #waitFor: 'tf init'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "plan"
      pwd
      cd CloudStorage
      pwd
      echo "plan ended"
      terraform plan -var-file=variables.tfvars -out=tf.plan 
      terraform show -json tf.plan >tf.json
      #cat tf.json
# [END tf-plan]

# [START Terraform plan scanning ]
- id: 'Plan Scanning with Checkov'
  name: 'python'
  #waitFor: 'tf plan'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
      echo "*****************"
      pip install checkov
      echo "**********install*******"
      cd CloudStorage
      checkov -f tf.json -o json >result.json #--skip-check=CKV_GCP*
      if [ $? == 1 ]; then
        echo "issues in scan, exiting"
        exit 1
      fi
      echo "*****************"
# [END Terraform plan scanning]  

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd ./CloudStorage
      #terraform apply -var-file="variables.tfvars" -auto-approve || exit 1
# [END tf-apply]      

options:
  logging: CLOUD_LOGGING_ONLY
